# Funding platforms for this project
# See: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# GitHub Sponsors username
github: [cschuman]

# Other platforms (uncomment and configure as needed)
# patreon: username
# open_collective: wastewater-disease-prediction
# ko_fi: username
# tidelift: npm/package-name
# community_bridge: project-name
# liberapay: username
# issuehunt: username
# otechie: username
# lfx_crowdfunding: project-name

# Custom funding URLs (up to 4)
# custom: ["https://your-funding-page.com"]
